version: '3.1'
services:
    appsec-assignment4:
        image: myimage1:latest
        restart: "no"
        ports:
            - 8080:5000
        secrets:
            - secret_key
            - csrf_secret_key
        deploy:
            replicas: 4
secrets:
  secret_key:
    file: AppSec-Assignment4/secret_key
  csrf_secret_key:
    file: AppSec-Assignment4/csrf_secret_key
